services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "5173:5173"
        environment:
            - VITE_API_URL=http://localhost:8080
        develop:
          watch:
            - action: sync
              path: ./src
              target: /app/src
            - action: rebuild
              path: ./package.json