FROM golang:1.25.3

WORKDIR /app

# Install Air
RUN go install github.com/air-verse/air@latest

# Copy go.mod/go.sum first for caching
COPY src/go.* ./

# Download all dependencies
RUN go mod download

# Copy source
COPY src/ .

# Run Air (hot reload)
CMD ["air"]