FROM golang:1.25.3 AS builder

WORKDIR /app
COPY go.* ./
RUN go mod download
COPY . .
RUN go build -o mock_courier .

FROM gcr.io/distroless/base-debian12
WORKDIR /app
COPY --from=builder /app/mock_courier .
CMD ["./mock_courier"]